# Generated by Django 3.2.7 on 2021-09-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0002_auto_20210915_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='long_name',
            new_name='desc',
        ),
    ]
